apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: razorpay-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: anuj55149/razorpay-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9020
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PAYMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PAYMENT_DB_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9020
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: razorpay-core
spec:
  selector:
    app: payment-service
  ports:
    - port: 80
      targetPort: 9020
