spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/Anuj-Kumar-Sharma/distributed-razrorpay-config
      username: anuj-kumar-sharma
      password: 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
      default-label: master

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}


---

spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    discovery:
      enabled: false

    config.server.git:
      uri: ${GIT_CONFIG_REPO}
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin.razorpay-core.svc.cluster.local:9411/api/v2/spans


